/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jd.core.v1.my_decompiler;

import org.jd.core.v1.ClassFileToJavaSourceDecompiler;
import java.io.File; // Import the File class
import java.io.IOException; // Import the IOException class to handle errors
import java.io.FileWriter;

public class App {
    public static void main(String[] args) throws Exception {
        String inputJavaClassPath = args[0];
        String outputJavaSourcePath = args[1];

        /*
         * for (String arg : args) {
         * System.out.println("arg: " + arg); //debug
         * }
         */
        ClassFileToJavaSourceDecompiler decompiler = new ClassFileToJavaSourceDecompiler();

        MyLoader loader = new MyLoader();
        MyPrinter printer = new MyPrinter();
        decompiler.decompile(loader, printer, inputJavaClassPath);
        String source = printer.toString();
        System.out.println("SOURCE CODE DECOMPILED FROM: " + inputJavaClassPath + "\n");
        // System.out.println(source); //debug
        writeJavaSourceFile(source, outputJavaSourcePath);
    }

    private static void writeJavaSourceFile(String content, String path) {
        try {
            File myObj = new File(path);
            if (myObj.createNewFile()) {
                System.out.println("File created: " + myObj.getName());
            } else {
                System.out.println("File already exists.");
            }
            FileWriter myWriter = new FileWriter(path);
            myWriter.write(content);
            myWriter.close();
        } catch (IOException e) {
            System.out.println("An error occurred trying " + content + " to file path: " + path);
            e.printStackTrace();
        }
    }
}
